# Generated by Django 4.1.4 on 2022-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('numero_visuales', models.IntegerField()),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('numero_temporadas', models.IntegerField()),
                ('puntaje', models.IntegerField()),
            ],
        ),
    ]
