# Generated by Django 4.1.4 on 2022-12-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
