# Generated by Django 4.1.4 on 2022-12-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='movies_app.movie'),
        ),
    ]
