# Generated by Django 4.1.4 on 2022-12-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_puntaje',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='puntaje',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
