# Generated by Django 4.1.4 on 2022-12-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_movie_num_puntaje_alter_movie_puntaje_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='num_puntaje',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='puntaje',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.user')),
            ],
            options={
                'unique_together': {('user', 'movie')},
                'index_together': {('user', 'movie')},
            },
        ),
    ]
